/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package sensorconfiguration.swing.ui;

import java.awt.Color;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.HashMap;
import java.util.logging.FileHandler;
import java.util.logging.Handler;
import java.util.logging.Level;
import java.util.logging.LogManager;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import javax.swing.UIManager;
import javax.swing.UIManager.LookAndFeelInfo;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.event.ChangeEvent;
import javax.swing.table.DefaultTableModel;
import rtpmt.logging.HTMLFormatter;
import rtpmt.packages.Config;
import rtpmt.packages.Package;
import rtpmt.packages.Sensor;

/**
 *
 * @author Kumar
 */
public class SensorConfigurator extends javax.swing.JFrame {
    private static final long serialVersionUID = 1L;

    /**
     * Declare UI Event Handler Object
     *
     */
    UIEventHandler eventHandler;

    /**
     * Creates new form MainUI
     */
    public SensorConfigurator() {
        try {
            for (LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException e) {
             // If Nimbus is not available, you can set the GUI to another look and feel.

        } catch (IllegalAccessException e) {
            // If Nimbus is not available, you can set the GUI to another look and feel.
        } catch (InstantiationException e) {
            // If Nimbus is not available, you can set the GUI to another look and feel.
        } catch (UnsupportedLookAndFeelException e) {
            // If Nimbus is not available, you can set the GUI to another look and feel.
        }
        initComponents();
        try {
            setupLogger();
        } catch (IOException ex) {
            Logger.getLogger(SensorConfigurator.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtLog.addMouseListener(new ContextMenuMouseListener());
        try {
            eventHandler = new UIEventHandler(this);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(SensorConfigurator.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    // Create a FileHandler and attach it to the root logger.
   // Create a MyHtmlFormatter and attach to the FileHandler.
   public static void setupLogger() throws IOException {
      Logger rootLogger = Logger.getLogger("");
      Handler htmlFileHandler = new FileHandler("log.html");
      HTMLFormatter htmlFormatter = new HTMLFormatter();
      rootLogger.addHandler(htmlFileHandler);
      htmlFileHandler.setFormatter(htmlFormatter);
      FileInputStream fis =  new FileInputStream("logging.properties");
        LogManager.getLogManager().readConfiguration(fis);
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jlblSensorStatus = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtComments = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtxtTuckId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxtPackageId = new javax.swing.JTextField();
        temPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        vibThreshold = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        vibTime = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        vibTimeThreshold = new javax.swing.JSpinner();
        jLabel32 = new javax.swing.JLabel();
        temPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        tempThreshold = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        tempTime = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        tempTimeThreshold = new javax.swing.JSpinner();
        jLabel30 = new javax.swing.JLabel();
        temPanel2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        shockThreshold = new javax.swing.JSpinner();
        jLabel19 = new javax.swing.JLabel();
        jbConfigure = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jbtnConnect = new javax.swing.JButton();
        validationLabel = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jlblSensorId = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        humidtyPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        humThreshold = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        humTime = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        humTimeThreshold = new javax.swing.JSpinner();
        jLabel34 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jProgressBar2 = new javax.swing.JProgressBar();
        JbtnSaveToServer1 = new javax.swing.JButton();
        JbtnSave = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jlblPackageId = new javax.swing.JLabel();
        jlblComments = new javax.swing.JLabel();
        jlblTruckId = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jlblSensorId1 = new javax.swing.JLabel();
        jbtnClearData = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtblLocalData = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtLog = new javax.swing.JTextArea();
        btnSaveAsCSV = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sensor Configurator");
        setBackground(java.awt.SystemColor.textHighlight);
        setIconImages(null);

        jTabbedPane1.setBackground(java.awt.Color.gray);
        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(1000, 615));
        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });
        jTabbedPane1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTabbedPane1FocusGained(evt);
            }
        });

        jlblSensorStatus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlblSensorStatus.setForeground(new java.awt.Color(255, 0, 0));
        jlblSensorStatus.setText("Not Connected");

        jtxtComments.setColumns(20);
        jtxtComments.setRows(5);
        jScrollPane1.setViewportView(jtxtComments);

        jLabel1.setText("Comments");

        jLabel2.setText("Truck Id");

        jtxtTuckId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTuckIdActionPerformed(evt);
            }
        });

        jLabel3.setText("Package Id");

        jtxtPackageId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPackageIdActionPerformed(evt);
            }
        });

        temPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Vibration"));
        temPanel.setAutoscrolls(true);

        jLabel4.setText("Threshold");

        vibThreshold.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 20.0d, 0.5d));

        jLabel5.setText("Time Interval");

        vibTime.setModel(new javax.swing.SpinnerNumberModel(0, 0, 3600, 1));

        jLabel6.setText("sec");

        jLabel7.setText("g value");

        jLabel31.setText("After Threshold Time Interval");

        vibTimeThreshold.setModel(new javax.swing.SpinnerNumberModel(0, 0, 3600, 1));

        jLabel32.setText("sec");

        org.jdesktop.layout.GroupLayout temPanelLayout = new org.jdesktop.layout.GroupLayout(temPanel);
        temPanel.setLayout(temPanelLayout);
        temPanelLayout.setHorizontalGroup(
            temPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(temPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(temPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel31)
                    .add(temPanelLayout.createSequentialGroup()
                        .add(temPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(temPanelLayout.createSequentialGroup()
                                .add(vibThreshold, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 82, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(18, 18, 18)
                                .add(jLabel7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 71, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jLabel4))
                        .add(79, 79, 79)
                        .add(jLabel5))
                    .add(temPanelLayout.createSequentialGroup()
                        .add(temPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(temPanelLayout.createSequentialGroup()
                                .add(250, 250, 250)
                                .add(vibTime, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 82, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(vibTimeThreshold))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(temPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel32)
                            .add(jLabel6))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        temPanelLayout.setVerticalGroup(
            temPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, temPanelLayout.createSequentialGroup()
                .add(10, 10, 10)
                .add(temPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel5)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel4))
                .add(18, 18, 18)
                .add(temPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(vibThreshold)
                    .add(jLabel7)
                    .add(temPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jLabel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(vibTime)))
                .add(18, 18, 18)
                .add(jLabel31)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(temPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(vibTimeThreshold)
                    .add(jLabel32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        temPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Temperature"));
        temPanel1.setAutoscrolls(true);

        jLabel12.setText("Threshold");

        tempThreshold.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), null, null, Double.valueOf(0.5d)));

        jLabel13.setText("Time Interval");

        tempTime.setModel(new javax.swing.SpinnerNumberModel(0, 0, 3600, 1));
        tempTime.setValue(1);

        jLabel14.setText("sec");

        jLabel15.setText("farenheit");

        jLabel29.setText("After Threshold Time Interval");

        tempTimeThreshold.setModel(new javax.swing.SpinnerNumberModel(0, 0, 3600, 1));

        jLabel30.setText("sec");

        org.jdesktop.layout.GroupLayout temPanel1Layout = new org.jdesktop.layout.GroupLayout(temPanel1);
        temPanel1.setLayout(temPanel1Layout);
        temPanel1Layout.setHorizontalGroup(
            temPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(temPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(temPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(temPanel1Layout.createSequentialGroup()
                        .add(temPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(tempThreshold, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 82, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel12))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(temPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(temPanel1Layout.createSequentialGroup()
                                .add(jLabel15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 71, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(82, 82, 82)
                                .add(tempTime, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 82, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel14))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, temPanel1Layout.createSequentialGroup()
                                .add(jLabel13)
                                .add(31, 31, 31))))
                    .add(jLabel29)
                    .add(temPanel1Layout.createSequentialGroup()
                        .add(tempTimeThreshold, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 327, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel30)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        temPanel1Layout.setVerticalGroup(
            temPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, temPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(temPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel12)
                    .add(jLabel13))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(temPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(temPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                        .add(jLabel15, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(tempThreshold)
                        .add(tempTime))
                    .add(jLabel14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jLabel29)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(temPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(tempTimeThreshold, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel30, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        temPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Shock"));
        temPanel2.setAutoscrolls(true);

        jLabel16.setText("Threshold");

        shockThreshold.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 200.0d, 0.5d));

        jLabel19.setText("g value");

        org.jdesktop.layout.GroupLayout temPanel2Layout = new org.jdesktop.layout.GroupLayout(temPanel2);
        temPanel2.setLayout(temPanel2Layout);
        temPanel2Layout.setHorizontalGroup(
            temPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(temPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(temPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel16)
                    .add(temPanel2Layout.createSequentialGroup()
                        .add(shockThreshold, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 200, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jLabel19, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 71, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        temPanel2Layout.setVerticalGroup(
            temPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, temPanel2Layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jLabel16)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(temPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(shockThreshold, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel19, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .add(83, 83, 83))
        );

        jbConfigure.setText("Configure");
        jbConfigure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConfigureActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel28.setText("Sensor Status :");

        jbtnConnect.setText("Connect");
        jbtnConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchForPorts(evt);
            }
        });

        validationLabel.setBackground(java.awt.Color.red);
        validationLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        validationLabel.setForeground(new java.awt.Color(204, 0, 51));

        jLabel17.setText("Sensor Id");
        jLabel17.setToolTipText("");

        jlblSensorId.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jlblSensorId.setForeground(new java.awt.Color(51, 0, 204));
        jlblSensorId.setText("xxxxxxxx");

        jButton2.setText("Restore Deafult Configuration");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        humidtyPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Humidty"));

        jLabel8.setText("Threshold");

        humThreshold.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), null, null, Double.valueOf(0.5d)));

        jLabel9.setText("Time Interval");

        humTime.setModel(new javax.swing.SpinnerNumberModel(0, 0, 3600, 1));

        jLabel10.setText("sec");

        jLabel11.setText("%");

        jLabel33.setText("After Threshold Time Interval");

        humTimeThreshold.setModel(new javax.swing.SpinnerNumberModel(0, 0, 3600, 1));

        jLabel34.setText("sec");

        org.jdesktop.layout.GroupLayout humidtyPanelLayout = new org.jdesktop.layout.GroupLayout(humidtyPanel);
        humidtyPanel.setLayout(humidtyPanelLayout);
        humidtyPanelLayout.setHorizontalGroup(
            humidtyPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(humidtyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(humidtyPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(humidtyPanelLayout.createSequentialGroup()
                        .add(humidtyPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(humThreshold, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 82, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel8))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel11, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 71, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(10, 10, 10)
                        .add(humidtyPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel9)
                            .add(humidtyPanelLayout.createSequentialGroup()
                                .add(humTime, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 82, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel10)))
                        .add(12, 12, 12))
                    .add(humidtyPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(humidtyPanelLayout.createSequentialGroup()
                            .add(humTimeThreshold)
                            .add(10, 10, 10)
                            .add(jLabel34)
                            .add(171, 171, 171))
                        .add(humidtyPanelLayout.createSequentialGroup()
                            .add(jLabel33)
                            .add(102, 102, 102)))))
        );
        humidtyPanelLayout.setVerticalGroup(
            humidtyPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, humidtyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(humidtyPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jLabel10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(humidtyPanelLayout.createSequentialGroup()
                        .add(humidtyPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel8)
                            .add(jLabel9))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(humidtyPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jLabel11, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(humThreshold)
                            .add(humTime))))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 18, Short.MAX_VALUE)
                .add(jLabel33)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(humidtyPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(humTimeThreshold, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(15, 15, 15))
        );

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(32, 32, 32)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(validationLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 715, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel1)
                            .add(jLabel2))
                        .add(18, 18, 18)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jtxtTuckId, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 264, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 267, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .add(jPanel1Layout.createSequentialGroup()
                .add(24, 24, 24)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(temPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(temPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 41, Short.MAX_VALUE)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jPanel1Layout.createSequentialGroup()
                                        .add(jLabel17, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                        .add(jlblSensorId, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 367, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(jPanel1Layout.createSequentialGroup()
                                        .add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(jtxtPackageId, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 358, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(48, 48, 48)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(temPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(humidtyPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(8, 8, 8)
                        .add(jLabel28)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jlblSensorStatus)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jbtnConnect, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 110, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(0, 0, Short.MAX_VALUE))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jButton2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 421, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(27, 27, 27)
                        .add(jbConfigure, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .add(10, 10, 10))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(validationLabel)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel2)
                            .add(jLabel3)
                            .add(jtxtPackageId, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jtxtTuckId, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(28, 28, 28)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel1)
                            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                .add(jLabel17)
                                .add(jlblSensorId))))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(33, 33, 33)
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(28, 28, 28)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel28)
                    .add(jbtnConnect)
                    .add(jlblSensorStatus, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 17, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(temPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(humidtyPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(18, 18, 18)
                        .add(temPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(47, 47, 47)
                        .add(temPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 97, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jbConfigure, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .add(jButton2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        humidtyPanel.getAccessibleContext().setAccessibleName("Humidity");

        jTabbedPane1.addTab("Settings", jPanel1);

        JbtnSaveToServer1.setText("Push to Server");
        JbtnSaveToServer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnSaveToServer1ActionPerformed(evt);
            }
        });

        JbtnSave.setText("Save Locally");
        JbtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnSaveActionPerformed(evt);
            }
        });

        jLabel23.setText("Package ID:");

        jLabel24.setText("Truck ID:");

        jLabel25.setText("Comments:");

        jlblPackageId.setText("xxxxxx");

        jlblComments.setText("xxxxxx");

        jlblTruckId.setText("xxxxxx");

        jLabel35.setText("Sensor ID:");

        jlblSensorId1.setText("xxxxxx");

        jbtnClearData.setText("Clear Sensor Data");
        jbtnClearData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnClearDataActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel5Layout = new org.jdesktop.layout.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .add(jProgressBar2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .add(jPanel5Layout.createSequentialGroup()
                .add(103, 103, 103)
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jLabel24)
                    .add(jLabel25))
                .add(26, 26, 26)
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel5Layout.createSequentialGroup()
                        .add(jlblTruckId, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 257, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jLabel23))
                    .add(jPanel5Layout.createSequentialGroup()
                        .add(jlblComments, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 257, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jLabel35)))
                .add(18, 18, 18)
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jlblPackageId, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 276, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jlblSensorId1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 214, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(53, 53, 53))
            .add(jPanel5Layout.createSequentialGroup()
                .add(304, 304, 304)
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jbtnClearData, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(JbtnSaveToServer1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(JbtnSave, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE))
                .add(311, 311, 311))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel5Layout.createSequentialGroup()
                .add(24, 24, 24)
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jlblPackageId, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 24, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel23)
                    .add(jlblTruckId, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 24, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel24))
                .add(32, 32, 32)
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel35)
                    .add(jlblSensorId1)
                    .add(jlblComments, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel25))
                .add(64, 64, 64)
                .add(JbtnSave, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 72, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(63, 63, 63)
                .add(JbtnSaveToServer1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 72, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(63, 63, 63)
                .add(jbtnClearData, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 62, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(46, 46, 46)
                .add(jProgressBar2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(24, 24, 24))
        );

        jTabbedPane1.addTab("Collect Data", jPanel5);

        jPanel3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel3FocusGained(evt);
            }
        });

        jtblLocalData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "SensorID", "PackageID", "Truck ID", "Time Stamp"
            }
        ));
        jScrollPane2.setViewportView(jtblLocalData);

        jButton4.setText("Push to Server");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel26.setText("Server Status");

        jLabel27.setText("Not Connected");

        jButton1.setText("Connect");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Save as CSV");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane2)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel26, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 126, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel27, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 97, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton1)
                .add(94, 94, 94)
                .add(jButton3)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 104, Short.MAX_VALUE)
                .add(jButton4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 345, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jButton4)
                    .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jLabel26, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 27, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jLabel27)
                        .add(jButton1)
                        .add(jButton3)))
                .add(4, 4, 4)
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 381, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(323, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Local Data", jPanel3);

        txtLog.setColumns(20);
        txtLog.setLineWrap(true);
        txtLog.setRows(5);
        txtLog.setBorder(null);
        jScrollPane4.setViewportView(txtLog);

        btnSaveAsCSV.setText("Save as CSV");
        btnSaveAsCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveAsCSVActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .add(btnSaveAsCSV, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 942, Short.MAX_VALUE)
                .addContainerGap())
            .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .add(jScrollPane4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 942, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .add(btnSaveAsCSV)
                .add(0, 565, Short.MAX_VALUE))
            .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel4Layout.createSequentialGroup()
                    .add(26, 26, 26)
                    .add(jScrollPane4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jTabbedPane1.addTab("logs", jPanel4);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 1031, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 751, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        eventHandler.pushLocalFilesToServer();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnSaveAsCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveAsCSVActionPerformed

        //Create a file chooser
        final JFileChooser fc;
        fc = new JFileChooser();
        int returnVal = fc.showSaveDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            try {
                File file = fc.getSelectedFile();
                //This is where a real application would open the file.
                System.out.print(file.getName());
                eventHandler.generateCSV(file);
                handleError(file.getName() + " successfully generated");
            } catch (FileNotFoundException ex) {
                handleError(ex.getMessage());
                Logger.getLogger(SensorConfigurator.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(SensorConfigurator.class.getName()).log(Level.SEVERE, null, ex);
                handleError("Couldn't able to create the file. Try again later");
            }
        } else {
        }
    }//GEN-LAST:event_btnSaveAsCSVActionPerformed

    private void jTabbedPane1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTabbedPane1FocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTabbedPane1FocusGained

    private void jPanel3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel3FocusGained
        // TODO add your handling code here:
        
     
    }//GEN-LAST:event_jPanel3FocusGained

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        // TODO add your handling code here:
        JTabbedPane panel = (JTabbedPane) evt.getSource();
        if(panel.getSelectedIndex() == 2){
            clearLocalDataTable();
            eventHandler.populateLocalData();
        }

    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void JbtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnSaveActionPerformed
        // TODO add your handling code here:
        eventHandler.saveDataLocally();
    }//GEN-LAST:event_JbtnSaveActionPerformed

    private void JbtnSaveToServer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnSaveToServer1ActionPerformed
        // TODO add your handling code here:
        eventHandler.pushToServer();
    }//GEN-LAST:event_JbtnSaveToServer1ActionPerformed

    private void jbtnClearDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnClearDataActionPerformed
        // TODO add your handling code here:
        eventHandler.clearSensorData();
    }//GEN-LAST:event_jbtnClearDataActionPerformed

    //Reset and Configure
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        eventHandler.restoreDefaultConfig();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void searchForPorts(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchForPorts
        // TODO add your handling code here:
        eventHandler.initSerialPort();
    }//GEN-LAST:event_searchForPorts

    private void jbConfigureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConfigureActionPerformed
        // TODO add your handling code here:
        try{
            Package pack = new Package();
            System.out.println(jlblSensorId.getText());

            String sensorId = jlblSensorId.getText();
            pack.setSensorId(sensorId);
            if(!jtxtPackageId.getText().equals("") && !jtxtTuckId.getText().equals("") && !jtxtComments.getText().equals("")){

                if(jtxtPackageId.getText().length() > 20){
                    handleError("Length of package Id should be below 20");
                    return;
                }
                if(jtxtTuckId.getText().length() > 20){
                    handleError("Length of truck Id should be below 20");
                    return;
                }
                if(jtxtComments.getText().length() > 80){
                    handleError("Length of comments should be below 80");
                    return;
                }
                pack.setPackageId(jtxtPackageId.getText());
                pack.setTruckId(jtxtTuckId.getText());
                pack.setComments(jtxtComments.getText());
                //temperature
                pack.setTemperatureTimePeriod((Integer) tempTime.getValue());
                pack.setMaxTemperatureThreshold((Double)tempThreshold.getValue());
                pack.setTemperatureAfterThresholdTimePeriod((Integer)tempTimeThreshold.getValue());

                //Humidity
                pack.setHumididtyTimePeriod((Integer) humTime.getValue());
                pack.setMaxHumidtyThreshold((Double)humThreshold.getValue());
                pack.setHumididtyAfterThresholdTimePeriod((Integer)humTimeThreshold.getValue());

                //Vibration
                pack.setVibrationTimePeriod((Integer) vibTime.getValue());
                pack.setMaxVibrationThreshold((Double)vibThreshold.getValue());
                pack.setVibrationAfterThresholdTimePeriod((Integer)vibTimeThreshold.getValue());

                //shock
                pack.setMaxShockThreshold((Double)shockThreshold.getValue());
                eventHandler.configureSensor(pack);
               
            }else{
                handleError("Make sure, you have Package Id, Truck Id and comments are Configured");
            }
        }catch(Exception ex){
            String logText = "Error :" + ex.toString() + "";
            Logger.getLogger(UIEventHandler.class.getName()).log(Level.SEVERE, null, ex);
            handleError("Not able to configure the sensor, try again");
        }
    }//GEN-LAST:event_jbConfigureActionPerformed

    private void jtxtPackageIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPackageIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPackageIdActionPerformed

    private void jtxtTuckIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTuckIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTuckIdActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        eventHandler.initServer(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        final JFileChooser fc;
        
        fc = new JFileChooser();
        fc.setDialogTitle("Select a folder");
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int returnVal = fc.showSaveDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            
            eventHandler.saveAsCSV(fc.getSelectedFile().getAbsolutePath());
        }
        else{
            handleError("Please select a folder");
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed
    
    public void clearLocalDataTable(){
        DefaultTableModel model = (DefaultTableModel) jtblLocalData.getModel();
         int rowCount =   model.getRowCount();
         for (int i = rowCount-1; i > 0 ; i--) {
            model.removeRow(i);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SensorConfigurator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SensorConfigurator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SensorConfigurator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SensorConfigurator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new SensorConfigurator().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JbtnSave;
    private javax.swing.JButton JbtnSaveToServer1;
    private javax.swing.JButton btnSaveAsCSV;
    private javax.swing.JSpinner humThreshold;
    private javax.swing.JSpinner humTime;
    private javax.swing.JSpinner humTimeThreshold;
    private javax.swing.JPanel humidtyPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    public javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    public javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jbConfigure;
    private javax.swing.JButton jbtnClearData;
    private javax.swing.JButton jbtnConnect;
    private javax.swing.JLabel jlblComments;
    private javax.swing.JLabel jlblPackageId;
    private javax.swing.JLabel jlblSensorId;
    private javax.swing.JLabel jlblSensorId1;
    private javax.swing.JLabel jlblSensorStatus;
    private javax.swing.JLabel jlblTruckId;
    public javax.swing.JTable jtblLocalData;
    private javax.swing.JTextArea jtxtComments;
    private javax.swing.JTextField jtxtPackageId;
    private javax.swing.JTextField jtxtTuckId;
    private javax.swing.JSpinner shockThreshold;
    private javax.swing.JPanel temPanel;
    private javax.swing.JPanel temPanel1;
    private javax.swing.JPanel temPanel2;
    private javax.swing.JSpinner tempThreshold;
    private javax.swing.JSpinner tempTime;
    private javax.swing.JSpinner tempTimeThreshold;
    public javax.swing.JTextArea txtLog;
    private javax.swing.JLabel validationLabel;
    private javax.swing.JSpinner vibThreshold;
    private javax.swing.JSpinner vibTime;
    private javax.swing.JSpinner vibTimeThreshold;
    // End of variables declaration//GEN-END:variables

    public void setConnected(boolean isSensorConnected) {

        if (isSensorConnected) {
            jlblSensorStatus.setText("Connected");
            jlblSensorStatus.setForeground(Color.getHSBColor((float)145.58823529411762, (float)78.16091954022988, (float)68.23529411764706));
            jbtnConnect.setText("Reconnect");
        } else {
            jlblSensorStatus.setText("Not Connected");
            jlblSensorStatus.setForeground(Color.RED);
            jbtnConnect.setText("Connect");
        }
    }

    public final void handleError(String msg) {
        JOptionPane.showMessageDialog(null, msg);
    }
    
    
    public void updateSensorDetail(Package pack){
        
        if( pack.getTruckId() != null && !pack.getTruckId().isEmpty()){
            updateTruckId(pack.getTruckId());
            updatePackageId(pack.getPackageId());
            updateComments(pack.getComments());            
        }
        HashMap<Sensor, Config> configList = pack.getConfigs();
        Config tempConfig = configList.get(Sensor.TEMPERATURE);
        tempTime.setValue(tempConfig.getTimePeriod());
        tempTimeThreshold.setValue(tempConfig.getAfterThresholdTimePeriod());
        tempThreshold.setValue(tempConfig.getMaxThreshold());
        
        tempConfig = configList.get(Sensor.HUMIDITY);
        humTime.setValue(tempConfig.getTimePeriod());
        humTimeThreshold.setValue(tempConfig.getAfterThresholdTimePeriod());
        humThreshold.setValue(tempConfig.getMaxThreshold());
        
        tempConfig = configList.get(Sensor.VIBRATION);
        vibTime.setValue(tempConfig.getTimePeriod());
        vibTimeThreshold.setValue(tempConfig.getAfterThresholdTimePeriod());
        vibThreshold.setValue(tempConfig.getMaxThreshold());
       
        tempConfig = configList.get(Sensor.SHOCK);
        shockThreshold.setValue(tempConfig.getMaxThreshold());
        

    }
    
    public void setSesnorId(String sensorId){
        jlblSensorId.setText(sensorId);
        jlblSensorId1.setText(sensorId);
    }

    private void updateTruckId(String truckId) {
        jtxtTuckId.setText(truckId);
        jlblTruckId.setText(truckId);
    }

    private void updatePackageId(String packageId) {
        jtxtPackageId.setText(packageId);
        jlblPackageId.setText(packageId);
    }

    private void updateComments(String comments) {
        jtxtComments.setText(comments);
        jlblComments.setText(comments);
    }

}
