/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package rtpt.desktop.client;

/**
 *
 * @author kumar
 */
public class RealTimePackageTracking extends javax.swing.JFrame {
    
    ComCommunicator comPort;
    /**
     * Creates new form RealTimePackageTracking
     */
    public RealTimePackageTracking() {
        initComponents();
        comPort = new ComCommunicator(this);
        comPort.searchForPorts();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcmbComPort = new javax.swing.JComboBox();
        jblComPort = new javax.swing.JLabel();
        jbtnConnect = new javax.swing.JButton();
        jlblStatus = new javax.swing.JLabel();
        jblConnectedStatus = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtLog = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Real Time Package Tracking");
        setName("RealTImePackageTracking");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jcmbComPort.setToolTipText("");

        jblComPort.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jblComPort.setText("Com Port :");

        jbtnConnect.setText("Connect");
        jbtnConnect.setToolTipText("");
        jbtnConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnConnectActionPerformed(evt);
            }
        });

        jlblStatus.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlblStatus.setText("Status :");
        jlblStatus.setToolTipText("");

        jblConnectedStatus.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jblConnectedStatus.setText("Not Connected");

        txtLog.setColumns(20);
        txtLog.setRows(5);
        jScrollPane1.setViewportView(txtLog);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Log :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jblComPort)
                                .addGap(18, 18, 18)
                                .addComponent(jcmbComPort, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbtnConnect)
                                .addGap(18, 18, 18)
                                .addComponent(jlblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jblConnectedStatus))
                            .addComponent(jLabel1))
                        .addGap(0, 155, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcmbComPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jblComPort)
                    .addComponent(jbtnConnect)
                    .addComponent(jlblStatus)
                    .addComponent(jblConnectedStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                .addContainerGap())
        );

        jcmbComPort.getAccessibleContext().setAccessibleName("");

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnConnectActionPerformed
        //connect to the com port and make connection
         
        if(!comPort.getConnected())
        {
            comPort.connect();
            if(comPort.getConnected())
            {
                if(comPort.initIOStream())
                {
                    comPort.initListener();
                    jbtnConnect.setText("Disconnect");
                }
            }
        }
        else
        {
            comPort.disconnect();
            jbtnConnect.setText("Connect");
        }
    }//GEN-LAST:event_jbtnConnectActionPerformed
    
    /**
     * Window closing event
     * disconnect from com port before closing
     * @param evt 
     */
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        
        if(comPort.getConnected())
        {
             comPort.disconnect();
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RealTimePackageTracking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RealTimePackageTracking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RealTimePackageTracking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RealTimePackageTracking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new RealTimePackageTracking().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jblComPort;
    public javax.swing.JLabel jblConnectedStatus;
    private javax.swing.JButton jbtnConnect;
    public javax.swing.JComboBox jcmbComPort;
    private javax.swing.JLabel jlblStatus;
    public javax.swing.JTextArea txtLog;
    // End of variables declaration//GEN-END:variables
}
